
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}})}
async function body(req){try{return await req.json()}catch{return null}}
function b64u(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function key(env){return crypto.subtle.importKey("raw",new TextEncoder().encode(env.AUTH_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"])}
async function signSession(env,userId,version=0){const payload=b64u(new TextEncoder().encode(JSON.stringify({sub:userId,v:Number(version||0),exp:Date.now()+86400000})));const sig=b64u(await crypto.subtle.sign("HMAC",await key(env),new TextEncoder().encode(payload)));return payload+"."+sig}
async function sessionUser(req,env){const c=req.headers.get("Cookie")||"",m=c.match(/(?:^|;\s*)viva_session=([^;]+)/);if(!m||!env.AUTH_SECRET)return null;try{const [p,s]=m[1].split(".");if(!await crypto.subtle.verify("HMAC",await key(env),unb64u(s),new TextEncoder().encode(p)))return null;const x=JSON.parse(new TextDecoder().decode(unb64u(p)));if(!(x.exp>Date.now()))return null;const u=await env.DB.prepare("SELECT session_version FROM users WHERE id=?").bind(x.sub).first();return u && Number(u.session_version||0)===Number(x.v||0)?x.sub:null}catch{return null}}
async function auth(req,env){return await sessionUser(req,env)}
async function hashPassword(password,salt){return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),256))}
async function isMember(env,chatId,userId){const r=await env.DB.prepare("SELECT 1 ok FROM chat_members WHERE chat_id=? AND user_id=?").bind(chatId,userId).first();return !!r}
async function isAdmin(env,userId){const r=await env.DB.prepare("SELECT 1 ok FROM users WHERE id=? AND role='admin'").bind(userId).first();return !!r}
async function hasActiveSubscription(env,userId){const r=await env.DB.prepare("SELECT role,subscription_expires_at FROM users WHERE id=?").bind(userId).first();if(!r)return false;if(r.role==='admin')return true;return !!r.subscription_expires_at && Number(new Date(String(r.subscription_expires_at).replace(' ','T')+'Z').getTime())>Date.now()}
function originOK(req){const o=req.headers.get("Origin");return !o||o===new URL(req.url).origin}
const ALLOWED=new Set(["image/jpeg","image/png","image/webp","image/gif","audio/mpeg","audio/mp4","audio/wav","audio/ogg","audio/webm","application/pdf","text/plain","text/csv","application/zip","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation","video/mp4","video/webm"]);
async function recordLoginFailure(env,keyId){const now=new Date();const r=await env.DB.prepare("SELECT attempts FROM login_attempts WHERE key=?").bind(keyId).first();const attempts=Number(r?.attempts||0)+1;const locked=attempts>=5?new Date(now.getTime()+15*60*1000).toISOString().slice(0,19).replace('T',' '):null;await env.DB.prepare("INSERT INTO login_attempts(key,attempts,locked_until) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET attempts=excluded.attempts,locked_until=excluded.locked_until").bind(keyId,attempts,locked).run()}
let ready=false;const OKIMG=(s,m)=>typeof s==="string"&&s.length<=m&&/^data:image\/jpeg;base64,[A-Za-z0-9+\/=]+$/.test(s);
async function ensure(env){if(ready)return;for(const s of["ALTER TABLE users ADD COLUMN display_name TEXT","ALTER TABLE users ADD COLUMN about TEXT","ALTER TABLE users ADD COLUMN avatar TEXT","ALTER TABLE messages ADD COLUMN reply_to INTEGER","ALTER TABLE messages ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0","UPDATE chats SET kind='group' WHERE id=1 AND kind='private'","ALTER TABLE users ADD COLUMN last_seen_at TEXT","ALTER TABLE messages ADD COLUMN edited INTEGER NOT NULL DEFAULT 0","CREATE TABLE IF NOT EXISTS chat_reads(chat_id INTEGER NOT NULL,user_id TEXT NOT NULL,last_read_id INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(chat_id,user_id))","CREATE TABLE IF NOT EXISTS statuses(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,kind TEXT NOT NULL,body TEXT,bg TEXT,image TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT NOT NULL)"]){try{await env.DB.prepare(s).run()}catch{}}ready=true}
async function upsertUser(env,b){const nu=String(b?.username||"").trim(),pw=String(b?.password||""),role=b?.role==="admin"?"admin":"user",days=Math.min(3650,Math.max(1,Number(b?.days)||30));if(!/^[A-Za-z0-9_.-]{3,32}$/.test(nu))return json({error:"invalid_username"},400);if(pw.length<8)return json({error:"password_too_short"},400);const salt=crypto.getRandomValues(new Uint8Array(16)),hash=await hashPassword(pw,salt),enc=x=>btoa(String.fromCharCode(...x));const ex=await env.DB.prepare("SELECT id FROM users WHERE username=?").bind(nu).first();if(ex){await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,role=?,subscription_expires_at=datetime('now','+' || ? || ' days'),session_version=session_version+1 WHERE id=?").bind(enc(hash),enc(salt),role,days,ex.id).run();return json({ok:true,username:nu,role,created:false})}const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,username,role,subscription_expires_at,password_hash,password_salt) VALUES(?,?,?,datetime('now','+' || ? || ' days'),?,?)").bind(id,nu,role,days,enc(hash),enc(salt)).run();await env.DB.prepare("INSERT OR IGNORE INTO chat_members(chat_id,user_id,role) VALUES(1,?,'member')").bind(id).run();return json({ok:true,username:nu,role,created:true})}
async function route(req,env){
 const u=new URL(req.url),p=u.pathname,method=req.method;
 if(p==="/api/health"&&method==="GET"){const r=await env.DB.prepare("SELECT 1 ok").first();return json({ok:r?.ok===1,storage:"D1-only",r2:false,auth_secret:!!env.AUTH_SECRET})}
 if(p==="/api/login"&&method==="POST"){
   const b=await body(req);if(!b?.username||!b?.password)return json({error:"credentials_required"},400);
   const ip=(req.headers.get('CF-Connecting-IP')||'unknown').slice(0,64), uname=String(b.username).trim().slice(0,100), keyId=`${ip}:${uname}`;
   const rl=await env.DB.prepare("SELECT attempts,locked_until FROM login_attempts WHERE key=?").bind(keyId).first();
   if(rl?.locked_until && Number(new Date(String(rl.locked_until).replace(' ','T')+'Z').getTime())>Date.now())return json({error:"too_many_attempts"},429,{"retry-after":"900"});
   const user=await env.DB.prepare("SELECT id,password_hash,password_salt,session_version FROM users WHERE username=?").bind(uname).first();
   if(!user||!user.password_hash||!user.password_salt){await recordLoginFailure(env,keyId);return json({error:"invalid_credentials"},401);}
   const got=await hashPassword(String(b.password),Uint8Array.from(atob(user.password_salt),c=>c.charCodeAt(0)));
   const expected=Uint8Array.from(atob(user.password_hash),c=>c.charCodeAt(0)); let diff=got.length^expected.length; for(let i=0;i<Math.max(got.length,expected.length);i++) diff|=(got[i]||0)^(expected[i]||0); const good=diff===0;
   if(!good){await recordLoginFailure(env,keyId);return json({error:"invalid_credentials"},401);}
   await env.DB.prepare("DELETE FROM login_attempts WHERE key=?").bind(keyId).run();
   try{await env.DB.prepare("UPDATE users SET last_login_at=datetime('now') WHERE id=?").bind(user.id).run()}catch{}
   const token=await signSession(env,user.id,user.session_version);return json({ok:true},200,{"set-cookie":`viva_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`})
 }
 if(p==="/api/logout"&&method==="POST")return json({ok:true},200,{"set-cookie":"viva_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"});
 const userId=await auth(req,env);
 if(!userId)return json({error:"unauthorized"},401);
 await ensure(env);
 if(p!=="/api/me" && p!=="/api/logout" && !(await hasActiveSubscription(env,userId)))return json({error:"subscription_expired"},403);
 if(method!=="GET"&&!originOK(req))return json({error:"bad_origin"},403);
 if(p==="/api/users"&&method==="GET"){const r=await env.DB.prepare("SELECT id,username,display_name,about,avatar FROM users WHERE id<>? ORDER BY username").bind(userId).all();return json(r.results)}
 if(p==="/api/me/profile"&&method==="POST"){const b=await body(req)||{},dn=String(b.display_name||"").trim().slice(0,40),ab=String(b.about||"").trim().slice(0,140);if(b.avatar!==undefined&&b.avatar!==""&&!OKIMG(b.avatar,150000))return json({error:"bad_avatar"},400);if(b.avatar===undefined)await env.DB.prepare("UPDATE users SET display_name=?,about=? WHERE id=?").bind(dn,ab,userId).run();else await env.DB.prepare("UPDATE users SET display_name=?,about=?,avatar=? WHERE id=?").bind(dn,ab,b.avatar||null,userId).run();return json({ok:true})}
 if(p==="/api/chats"&&method==="POST"){const b=await body(req),o=String(b?.user_id||"");const t=await env.DB.prepare("SELECT id FROM users WHERE id=?").bind(o).first();if(!t||o===userId)return json({error:"invalid_user"},400);const ex=await env.DB.prepare("SELECT c.id FROM chats c JOIN chat_members a ON a.chat_id=c.id AND a.user_id=? JOIN chat_members z ON z.chat_id=c.id AND z.user_id=? WHERE c.kind='private' LIMIT 1").bind(userId,o).first();if(ex)return json({id:ex.id});const c=await env.DB.prepare("INSERT INTO chats(kind,title) VALUES('private','') RETURNING id").first();await env.DB.prepare("INSERT INTO chat_members(chat_id,user_id,role) VALUES(?,?,'member'),(?,?,'member')").bind(c.id,userId,c.id,o).run();return json({id:c.id},201)}
 if(p==="/api/status"&&method==="GET"){await env.DB.prepare("DELETE FROM statuses WHERE expires_at<=datetime('now')").run();const r=await env.DB.prepare("SELECT s.id,s.user_id,s.kind,s.body,s.bg,s.image,s.created_at,COALESCE(NULLIF(u.display_name,''),u.username) name,u.avatar FROM statuses s JOIN users u ON u.id=s.user_id ORDER BY s.id").all();return json(r.results)}
 if(p==="/api/status"&&method==="POST"){const b=await body(req)||{},kind=b.kind==="image"?"image":"text",text=String(b.body||"").trim().slice(0,700);let img=null;if(kind==="image"){if(!OKIMG(b.image,400000))return json({error:"bad_image"},400);img=b.image}else if(!text)return json({error:"empty"},400);const bg=/^#[0-9a-f]{6}$/i.test(b.bg||"")?b.bg:"#0b8f6a";const r=await env.DB.prepare("INSERT INTO statuses(user_id,kind,body,bg,image,expires_at) VALUES(?,?,?,?,?,datetime('now','+24 hours')) RETURNING id").bind(userId,kind,text||null,bg,img).first();return json(r,201)}
 const sd=p.match(/^\/api\/status\/(\d+)$/);if(sd&&method==="DELETE"){await env.DB.prepare("DELETE FROM statuses WHERE id=? AND user_id=?").bind(Number(sd[1]),userId).run();return json({ok:true})}
 const rd=p.match(/^\/api\/chats\/(\d+)\/read$/);if(rd&&method==="POST"){const id=Number(rd[1]),b=await body(req),up=Number(b?.upto);if(!Number.isSafeInteger(up)||!(await isMember(env,id,userId)))return json({error:"forbidden"},403);await env.DB.prepare("INSERT INTO chat_reads(chat_id,user_id,last_read_id) VALUES(?,?,?) ON CONFLICT(chat_id,user_id) DO UPDATE SET last_read_id=MAX(last_read_id,excluded.last_read_id)").bind(id,userId,up).run();return json({ok:true})}
 if(p==="/api/admin/users"&&method==="POST"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);return upsertUser(env,await body(req)||{})}
 const em=p.match(/^\/api\/messages\/(\d+)$/);if(em&&method==="PUT"){const id=Number(em[1]),b=await body(req),t=String(b?.body||"").trim();if(!t||t.length>10000)return json({error:"invalid"},400);const r=await env.DB.prepare("UPDATE messages SET body=?,edited=1 WHERE id=? AND sender_id=? AND deleted=0 AND body IS NOT NULL AND created_at>datetime('now','-15 minutes')").bind(t,id,userId).run();if(!r.meta?.changes)return json({error:"cannot_edit"},403);await env.DB.prepare("UPDATE chats SET updated_at=datetime('now') WHERE id=(SELECT chat_id FROM messages WHERE id=?)").bind(id).run();return json({ok:true})}
 const dm=p.match(/^\/api\/messages\/(\d+)$/);if(dm&&method==="DELETE"){const id=Number(dm[1]);const r=await env.DB.prepare("UPDATE messages SET deleted=1 WHERE id=? AND sender_id=?").bind(id,userId).run();if(!r.meta?.changes)return json({error:"forbidden"},403);await env.DB.prepare("UPDATE chats SET updated_at=datetime('now') WHERE id=(SELECT chat_id FROM messages WHERE id=?)").bind(id).run();return json({ok:true})}
 if(p==="/api/groups"&&method==="POST"){const b=await body(req)||{},t=String(b.title||"").trim().slice(0,50),ids=[...new Set((Array.isArray(b.members)?b.members:[]).map(String))].filter(x=>x!==userId).slice(0,49);if(!t||!ids.length)return json({error:"title_and_members_required"},400);const ok=await env.DB.prepare(`SELECT id FROM users WHERE id IN (${ids.map(()=>"?").join(",")})`).bind(...ids).all();if(!ok.results.length)return json({error:"no_valid_members"},400);const c=await env.DB.prepare("INSERT INTO chats(kind,title) VALUES('group',?) RETURNING id").bind(t).first();const mem=[[userId,"admin"],...ok.results.map(x=>[x.id,"member"])];await env.DB.batch(mem.map(([u,r])=>env.DB.prepare("INSERT INTO chat_members(chat_id,user_id,role) VALUES(?,?,?)").bind(c.id,u,r)));return json({id:c.id},201)}
 const gm=p.match(/^\/api\/chats\/(\d+)\/members(?:\/([^\/]+))?$/);if(gm){const id=Number(gm[1]);if(!(await isMember(env,id,userId)))return json({error:"forbidden"},403);const ch=await env.DB.prepare("SELECT kind FROM chats WHERE id=?").bind(id).first();
  if(method==="GET"){const r=await env.DB.prepare("SELECT u.id,COALESCE(NULLIF(u.display_name,''),u.username) name,u.about,u.avatar,cm.role FROM chat_members cm JOIN users u ON u.id=cm.user_id WHERE cm.chat_id=? ORDER BY cm.role,name").bind(id).all();return json({kind:ch?.kind,members:r.results})}
  if(ch?.kind!=="group")return json({error:"not_group"},400);const mr=await env.DB.prepare("SELECT role FROM chat_members WHERE chat_id=? AND user_id=?").bind(id,userId).first(),ga=mr?.role==="admin"||await isAdmin(env,userId);
  if(method==="POST"){if(!ga)return json({error:"group_admin_required"},403);const b=await body(req),u=String(b?.user_id||""),n=await env.DB.prepare("SELECT COUNT(*) n FROM chat_members WHERE chat_id=?").bind(id).first();if(Number(n.n)>=50)return json({error:"group_full"},400);if(!(await env.DB.prepare("SELECT id FROM users WHERE id=?").bind(u).first()))return json({error:"invalid_user"},400);await env.DB.prepare("INSERT OR IGNORE INTO chat_members(chat_id,user_id,role) VALUES(?,?,'member')").bind(id,u).run();return json({ok:true})}
  if(method==="DELETE"){const u=decodeURIComponent(gm[2]||"");if(u!==userId&&!ga)return json({error:"group_admin_required"},403);await env.DB.prepare("DELETE FROM chat_members WHERE chat_id=? AND user_id=?").bind(id,u).run();return json({ok:true})}}
 if(p==="/api/me"&&method==="GET"){const r=await env.DB.prepare("SELECT id,username,role,subscription_expires_at,display_name,about,avatar FROM users WHERE id=?").bind(userId).first();return json(r||{},r?200:401)}
 if(p==="/api/chats"&&method==="GET"){await env.DB.prepare("UPDATE users SET last_seen_at=datetime('now') WHERE id=? AND (last_seen_at IS NULL OR last_seen_at<datetime('now','-30 seconds'))").bind(userId).run();const r=await env.DB.prepare(`SELECT c.id,c.kind,c.title,c.created_at,c.updated_at,(SELECT CASE WHEN m.deleted=1 THEN '🚫 این پیام حذف شد' ELSE COALESCE(m.body,'📎 رسانه') END FROM messages m WHERE m.chat_id=c.id ORDER BY m.id DESC LIMIT 1) last_message,(SELECT COUNT(*) FROM messages m3 WHERE m3.chat_id=c.id AND m3.sender_id<>cm.user_id AND m3.id>COALESCE((SELECT r.last_read_id FROM chat_reads r WHERE r.chat_id=c.id AND r.user_id=cm.user_id),0)) unread,(SELECT r.last_read_id FROM chat_reads r WHERE r.chat_id=c.id AND r.user_id<>cm.user_id AND c.kind='private' LIMIT 1) peer_read,(SELECT COALESCE(NULLIF(u.display_name,''),u.username) FROM chat_members m2 JOIN users u ON u.id=m2.user_id WHERE m2.chat_id=c.id AND m2.user_id<>cm.user_id AND c.kind='private' LIMIT 1) peer_name,(SELECT u.avatar FROM chat_members m2 JOIN users u ON u.id=m2.user_id WHERE m2.chat_id=c.id AND m2.user_id<>cm.user_id AND c.kind='private' LIMIT 1) peer_avatar,(SELECT u.last_seen_at FROM chat_members m2 JOIN users u ON u.id=m2.user_id WHERE m2.chat_id=c.id AND m2.user_id<>cm.user_id AND c.kind='private' LIMIT 1) peer_seen FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=? ORDER BY c.updated_at DESC`).bind(userId).all();return json(r.results)}
 const cm=p.match(/^\/api\/messages\/(\d+)$/);if(cm&&method==="GET"){const chatId=Number(cm[1]);if(!(await isMember(env,chatId,userId)))return json({error:"forbidden"},403);const r=await env.DB.prepare("SELECT id,sender_id,body,media_id,media_type,media_name,created_at,reply_to,deleted,edited,(SELECT CASE WHEN r.deleted=1 THEN NULL ELSE COALESCE(r.body,'📎 رسانه') END FROM messages r WHERE r.id=messages.reply_to) reply_body,(SELECT r.sender_id FROM messages r WHERE r.id=messages.reply_to) reply_sender,(SELECT COALESCE(NULLIF(u.display_name,''),u.username) FROM messages r JOIN users u ON u.id=r.sender_id WHERE r.id=messages.reply_to) reply_name,(SELECT COALESCE(NULLIF(u.display_name,''),u.username) FROM users u WHERE u.id=messages.sender_id) sender_name FROM messages WHERE chat_id=? ORDER BY id DESC LIMIT 100").bind(chatId).all();return json(r.results.reverse().map(m=>m.deleted?{...m,body:null,media_id:null,media_type:null,media_name:null}:m))}
 if(p==="/api/messages"&&method==="POST"){const b=await body(req);const text=String(b?.body||"").trim();if(!b?.chat_id||(!text&&!b.media_id))return json({error:"message_required"},400);if(text.length>10000)return json({error:"message_too_long"},413);const chatId=Number(b.chat_id);if(!Number.isSafeInteger(chatId)||!(await isMember(env,chatId,userId)))return json({error:"forbidden"},403);if(b.media_id){const m=await env.DB.prepare("SELECT id FROM media WHERE id=? AND owner_id=? AND complete=1 AND expires_at>datetime('now')").bind(b.media_id,userId).first();if(!m)return json({error:"invalid_media"},400)}let rt=null;if(b.reply_to){const q=await env.DB.prepare("SELECT id FROM messages WHERE id=? AND chat_id=?").bind(Number(b.reply_to),chatId).first();rt=q?q.id:null}const r=await env.DB.prepare("INSERT INTO messages(chat_id,sender_id,body,media_id,media_type,media_name,reply_to) VALUES(?,?,?,?,?,?,?) RETURNING id,created_at").bind(chatId,userId,text||null,b.media_id||null,b.media_type||null,b.media_name||null,rt).first();await env.DB.prepare("UPDATE chats SET updated_at=datetime('now') WHERE id=?").bind(chatId).run();return json(r,201)}
 if(p==="/api/media/init"&&method==="POST"){const b=await body(req);if(!b?.name||!ALLOWED.has(b.type)||!Number.isInteger(b.size)||b.size<=0)return json({error:"invalid_file_type_or_size"},400);if(b.type.startsWith("image/")&&b.size>5*1024*1024)return json({error:"image_over_5mb"},413);if(b.type.startsWith("audio/")&&b.size>20*1024*1024)return json({error:"audio_over_20mb"},413);if(!/^(image|audio)\//.test(b.type)&&b.size>20*1024*1024)return json({error:"file_over_20mb"},413);const r=await env.DB.prepare("INSERT INTO media(owner_id,name,mime,size,expires_at) VALUES(?,?,?,?,datetime('now','+3 days')) RETURNING id").bind(userId,String(b.name).slice(0,255),b.type,b.size).first();return json({media_id:r.id,chunk_size:1500000})}
 if(p==="/api/media/chunk"&&method==="POST"){const b=await body(req);if(!b?.media_id||!Number.isInteger(b.part)||b.part<0||typeof b.data_b64!=="string"||b.data_b64.length>2100000)return json({error:"invalid_chunk"},400);const m=await env.DB.prepare("SELECT owner_id,size FROM media WHERE id=? AND complete=0 AND expires_at>datetime('now')").bind(b.media_id).first();if(!m||m.owner_id!==userId)return json({error:"forbidden"},403);let raw;try{raw=atob(b.data_b64)}catch{return json({error:"bad_base64"},400)}if(raw.length>1500000)return json({error:"chunk_too_large"},413);const maxParts=Math.ceil(Number(m.size)/1500000);if(b.part>=maxParts)return json({error:"part_out_of_range"},400);await env.DB.prepare("INSERT OR REPLACE INTO media_chunks(media_id,part,data) VALUES(?,?,?)").bind(b.media_id,b.part,new Uint8Array([...raw].map(c=>c.charCodeAt(0)))).run();return json({ok:true})}
 if(p==="/api/media/complete"&&method==="POST"){const b=await body(req);const m=await env.DB.prepare("SELECT * FROM media WHERE id=? AND owner_id=? AND complete=0 AND expires_at>datetime('now')").bind(b?.media_id,userId).first();if(!m)return json({error:"not_found"},404);const expected=Math.ceil(Number(m.size)/1500000);const c=await env.DB.prepare("SELECT COALESCE(SUM(length(data)),0) bytes,COUNT(*) n,COALESCE(MIN(part),-1) minpart,COALESCE(MAX(part),-1) maxpart FROM media_chunks WHERE media_id=?").bind(m.id).first();if(Number(c.n)!==expected||Number(c.bytes)!==Number(m.size)||Number(c.minpart)!==0||Number(c.maxpart)!==expected-1)return json({error:"incomplete_upload"},400);await env.DB.prepare("UPDATE media SET complete=1 WHERE id=?").bind(m.id).run();return json({ok:true})}
 const mr=p.match(/^\/api\/media\/(\d+)$/);if(mr&&method==="GET"){const mediaId=Number(mr[1]);const access=await env.DB.prepare("SELECT me.* FROM media me WHERE me.id=? AND me.complete=1 AND me.expires_at>datetime('now') AND EXISTS(SELECT 1 FROM messages m JOIN chat_members cm ON cm.chat_id=m.chat_id WHERE m.media_id=me.id AND m.deleted=0 AND cm.user_id=?)").bind(mediaId,userId).first();if(!access)return new Response("Not found",{status:404});const parts=await env.DB.prepare("SELECT data FROM media_chunks WHERE media_id=? ORDER BY part").bind(mediaId).all();const total=parts.results.reduce((n,x)=>n+x.data.byteLength,0),out=new Uint8Array(total);let pos=0;for(const x of parts.results){const a=new Uint8Array(x.data);out.set(a,pos);pos+=a.length}return new Response(out,{headers:{"content-type":access.mime,"cache-control":"private,max-age=3600","x-content-type-options":"nosniff","content-disposition":/^(image|audio|video)\//.test(access.mime)||access.mime==="application/pdf"?"inline":"attachment; filename*=UTF-8''"+encodeURIComponent(access.name||"file")}})}
 if((p==="/api/admin/password"||p==="/api/me/password")&&method==="POST"){if(p.startsWith("/api/admin")&&!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const b=await body(req);if(!b?.password||String(b.password).length<12)return json({error:"password_too_short"},400);const salt=crypto.getRandomValues(new Uint8Array(16));const hash=await hashPassword(String(b.password),salt);const enc=x=>btoa(String.fromCharCode(...x));await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,session_version=session_version+1 WHERE id=?").bind(enc(hash),enc(salt),userId).run();return json({ok:true})}
 if((p==="/api/admin/username"||p==="/api/me/username")&&method==="POST"){if(p.startsWith("/api/admin")&&!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const b=await body(req),nu=String(b?.username||"").trim();if(!/^[A-Za-z0-9_.-]{3,32}$/.test(nu))return json({error:"invalid_username"},400);const ex=await env.DB.prepare("SELECT id FROM users WHERE username=? AND id<>?").bind(nu,userId).first();if(ex)return json({error:"username_taken"},409);await env.DB.prepare("UPDATE users SET username=? WHERE id=?").bind(nu,userId).run();return json({ok:true,username:nu})}
 if(p==="/api/admin/storage"&&method==="GET"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const meta=await env.DB.prepare("SELECT page_count,page_size FROM pragma_page_count(), pragma_page_size()").first().catch(()=>null);const media=await env.DB.prepare("SELECT COALESCE(SUM(size),0) bytes,COUNT(*) files FROM media WHERE complete=1").first();const messages=await env.DB.prepare("SELECT COUNT(*) count FROM messages").first();const dbBytes=Number(meta?.page_count||0)*Number(meta?.page_size||0);return json({db_bytes:dbBytes,media_bytes:Number(media?.bytes||0),files:Number(media?.files||0),messages:Number(messages?.count||0),limit_bytes:10*1024*1024*1024,exact:!!meta})}
 if(p==="/api/admin/users"&&method==="GET"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const r=await env.DB.prepare("SELECT id,username,role,subscription_expires_at,created_at FROM users ORDER BY id").all();return json(r.results)}
 if(p==="/api/admin/subscription"&&method==="POST"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const b=await body(req),days=Number(b?.days);if(!b?.user_id||!Number.isInteger(days)||days<1||days>3650)return json({error:"invalid"},400);const r=await env.DB.prepare("UPDATE users SET subscription_expires_at=datetime('now','+' || ? || ' days') WHERE id=?").bind(days,b.user_id).run();if(!r.meta?.changes)return json({error:"user_not_found"},404);return json({ok:true})}
 return new Response("Not found",{status:404})
}
export default {async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname.startsWith("/api/")){try{return await route(req,env)}catch(e){return json({error:"server_error",message:String(e?.message||e)},500)}}return env.ASSETS.fetch(req)},async scheduled(controller,env,ctx){ctx.waitUntil((async()=>{await env.DB.prepare("DELETE FROM media_chunks WHERE media_id IN (SELECT id FROM media WHERE expires_at<=datetime('now') OR (complete=0 AND created_at<=datetime('now','-1 day')))").run();await env.DB.prepare("DELETE FROM media WHERE expires_at<=datetime('now') OR (complete=0 AND created_at<=datetime('now','-1 day'))").run()})())}}
