
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}})}
async function body(req){try{return await req.json()}catch{return null}}
function b64u(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function key(env){return crypto.subtle.importKey("raw",new TextEncoder().encode(env.AUTH_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"])}
async function signSession(env,userId,version=0){const payload=b64u(new TextEncoder().encode(JSON.stringify({sub:userId,v:Number(version||0),exp:Date.now()+86400000})));const sig=b64u(await crypto.subtle.sign("HMAC",await key(env),new TextEncoder().encode(payload)));return payload+"."+sig}
async function sessionUser(req,env){const c=req.headers.get("Cookie")||"",m=c.match(/(?:^|;\s*)viva_session=([^;]+)/);if(!m||!env.AUTH_SECRET)return null;try{const [p,s]=m[1].split(".");if(!await crypto.subtle.verify("HMAC",await key(env),unb64u(s),new TextEncoder().encode(p)))return null;const x=JSON.parse(new TextDecoder().decode(unb64u(p)));if(!(x.exp>Date.now()))return null;const u=await env.DB.prepare("SELECT session_version FROM users WHERE id=?").bind(x.sub).first();return u && Number(u.session_version||0)===Number(x.v||0)?x.sub:null}catch{return null}}
async function auth(req,env){return await sessionUser(req,env)}
async function hashPassword(password,salt){return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:100000,hash:"SHA-256"},await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),256))}
async function isMember(env,chatId,userId){const r=await env.DB.prepare("SELECT 1 ok FROM chat_members WHERE chat_id=? AND user_id=?").bind(chatId,userId).first();return !!r}
async function isAdmin(env,userId){const r=await env.DB.prepare("SELECT 1 ok FROM users WHERE id=? AND role='admin'").bind(userId).first();return !!r}
async function hasActiveSubscription(env,userId){const r=await env.DB.prepare("SELECT role,subscription_expires_at FROM users WHERE id=?").bind(userId).first();if(!r)return false;if(r.role==='admin')return true;return !!r.subscription_expires_at && Number(new Date(String(r.subscription_expires_at).replace(' ','T')+'Z').getTime())>Date.now()}
function originOK(req){const o=req.headers.get("Origin");return !o||o===new URL(req.url).origin}
const ALLOWED=new Set(["image/jpeg","image/png","image/webp","image/gif","audio/mpeg","audio/mp4","audio/wav","audio/ogg","audio/webm"]);
async function recordLoginFailure(env,keyId){const now=new Date();const r=await env.DB.prepare("SELECT attempts FROM login_attempts WHERE key=?").bind(keyId).first();const attempts=Number(r?.attempts||0)+1;const locked=attempts>=5?new Date(now.getTime()+15*60*1000).toISOString().slice(0,19).replace('T',' '):null;await env.DB.prepare("INSERT INTO login_attempts(key,attempts,locked_until) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET attempts=excluded.attempts,locked_until=excluded.locked_until").bind(keyId,attempts,locked).run()}
async function route(req,env){
 const u=new URL(req.url),p=u.pathname,method=req.method;
 if(p==="/api/health"&&method==="GET"){const r=await env.DB.prepare("SELECT 1 ok").first();return json({ok:r?.ok===1,storage:"D1-only",r2:false})}
 if(p==="/api/login"&&method==="POST"){
   const b=await body(req);if(!b?.username||!b?.password)return json({error:"credentials_required"},400);
   const ip=(req.headers.get('CF-Connecting-IP')||'unknown').slice(0,64), uname=String(b.username).trim().slice(0,100), keyId=`${ip}:${uname}`;
   const rl=await env.DB.prepare("SELECT attempts,locked_until FROM login_attempts WHERE key=?").bind(keyId).first();
   if(rl?.locked_until && Number(new Date(String(rl.locked_until).replace(' ','T')+'Z').getTime())>Date.now())return json({error:"too_many_attempts"},429,{"retry-after":"900"});
   const user=await env.DB.prepare("SELECT id,password_hash,password_salt,session_version FROM users WHERE username=?").bind(uname).first();
   if(!user||!user.password_hash||!user.password_salt){await recordLoginFailure(env,keyId);return json({error:"invalid_credentials"},401);}
   const got=await hashPassword(String(b.password),Uint8Array.from(atob(user.password_salt),c=>c.charCodeAt(0)));
   const expected=Uint8Array.from(atob(user.password_hash),c=>c.charCodeAt(0)); let diff=got.length^expected.length; for(let i=0;i<Math.max(got.length,expected.length);i++) diff|=(got[i]||0)^(expected[i]||0); const good=diff===0;
   if(!good){await recordLoginFailure(env,keyId);return json({error:"invalid_credentials"},401);}
   await env.DB.prepare("DELETE FROM login_attempts WHERE key=?").bind(keyId).run();
   await env.DB.prepare("UPDATE users SET last_login_at=datetime('now') WHERE id=?").bind(user.id).run();
   const token=await signSession(env,user.id,user.session_version);return json({ok:true},{headers:{"set-cookie":`viva_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`}})
 }
 if(p==="/api/logout"&&method==="POST")return json({ok:true},{headers:{"set-cookie":"viva_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"}});
 const userId=await auth(req,env);
 if(!userId)return json({error:"unauthorized"},401);
 if(p!=="/api/me" && p!=="/api/logout" && !(await hasActiveSubscription(env,userId)))return json({error:"subscription_expired"},403);
 if(method!=="GET"&&!originOK(req))return json({error:"bad_origin"},403);
 if(p==="/api/me"&&method==="GET"){const r=await env.DB.prepare("SELECT id,username,role,subscription_expires_at FROM users WHERE id=?").bind(userId).first();return json(r||{},r?200:401)}
 if(p==="/api/chats"&&method==="GET"){const r=await env.DB.prepare(`SELECT c.id,c.kind,c.title,c.created_at,c.updated_at,(SELECT body FROM messages m WHERE m.chat_id=c.id ORDER BY m.id DESC LIMIT 1) last_message FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=? ORDER BY c.updated_at DESC`).bind(userId).all();return json(r.results)}
 const cm=p.match(/^\/api\/messages\/(\d+)$/);if(cm&&method==="GET"){const chatId=Number(cm[1]);if(!(await isMember(env,chatId,userId)))return json({error:"forbidden"},403);const r=await env.DB.prepare("SELECT id,sender_id,body,media_id,media_type,media_name,created_at FROM messages WHERE chat_id=? ORDER BY id DESC LIMIT 100").bind(chatId).all();return json(r.results.reverse())}
 if(p==="/api/messages"&&method==="POST"){const b=await body(req);const text=String(b?.body||"").trim();if(!b?.chat_id||(!text&&!b.media_id))return json({error:"message_required"},400);if(text.length>10000)return json({error:"message_too_long"},413);const chatId=Number(b.chat_id);if(!Number.isSafeInteger(chatId)||!(await isMember(env,chatId,userId)))return json({error:"forbidden"},403);if(b.media_id){const m=await env.DB.prepare("SELECT id FROM media WHERE id=? AND owner_id=? AND complete=1 AND expires_at>datetime('now')").bind(b.media_id,userId).first();if(!m)return json({error:"invalid_media"},400)}const r=await env.DB.prepare("INSERT INTO messages(chat_id,sender_id,body,media_id,media_type,media_name) VALUES(?,?,?,?,?,?) RETURNING id,created_at").bind(chatId,userId,text||null,b.media_id||null,b.media_type||null,b.media_name||null).first();await env.DB.prepare("UPDATE chats SET updated_at=datetime('now') WHERE id=?").bind(chatId).run();return json(r,201)}
 if(p==="/api/media/init"&&method==="POST"){const b=await body(req);if(!b?.name||!ALLOWED.has(b.type)||!Number.isInteger(b.size)||b.size<=0)return json({error:"invalid_file_type_or_size"},400);if(b.type.startsWith("image/")&&b.size>5*1024*1024)return json({error:"image_over_5mb"},413);if(b.type.startsWith("audio/")&&b.size>20*1024*1024)return json({error:"audio_over_20mb"},413);const r=await env.DB.prepare("INSERT INTO media(owner_id,name,mime,size,expires_at) VALUES(?,?,?,?,datetime('now','+3 days')) RETURNING id").bind(userId,String(b.name).slice(0,255),b.type,b.size).first();return json({media_id:r.id,chunk_size:1500000})}
 if(p==="/api/media/chunk"&&method==="POST"){const b=await body(req);if(!b?.media_id||!Number.isInteger(b.part)||b.part<0||typeof b.data_b64!=="string"||b.data_b64.length>2100000)return json({error:"invalid_chunk"},400);const m=await env.DB.prepare("SELECT owner_id,size FROM media WHERE id=? AND complete=0 AND expires_at>datetime('now')").bind(b.media_id).first();if(!m||m.owner_id!==userId)return json({error:"forbidden"},403);let raw;try{raw=atob(b.data_b64)}catch{return json({error:"bad_base64"},400)}if(raw.length>1500000)return json({error:"chunk_too_large"},413);const maxParts=Math.ceil(Number(m.size)/1500000);if(b.part>=maxParts)return json({error:"part_out_of_range"},400);await env.DB.prepare("INSERT OR REPLACE INTO media_chunks(media_id,part,data) VALUES(?,?,?)").bind(b.media_id,b.part,new Uint8Array([...raw].map(c=>c.charCodeAt(0)))).run();return json({ok:true})}
 if(p==="/api/media/complete"&&method==="POST"){const b=await body(req);const m=await env.DB.prepare("SELECT * FROM media WHERE id=? AND owner_id=? AND complete=0 AND expires_at>datetime('now')").bind(b?.media_id,userId).first();if(!m)return json({error:"not_found"},404);const expected=Math.ceil(Number(m.size)/1500000);const c=await env.DB.prepare("SELECT COALESCE(SUM(length(data)),0) bytes,COUNT(*) n,COALESCE(MIN(part),-1) minpart,COALESCE(MAX(part),-1) maxpart FROM media_chunks WHERE media_id=?").bind(m.id).first();if(Number(c.n)!==expected||Number(c.bytes)!==Number(m.size)||Number(c.minpart)!==0||Number(c.maxpart)!==expected-1)return json({error:"incomplete_upload"},400);await env.DB.prepare("UPDATE media SET complete=1 WHERE id=?").bind(m.id).run();return json({ok:true})}
 const mr=p.match(/^\/api\/media\/(\d+)$/);if(mr&&method==="GET"){const mediaId=Number(mr[1]);const access=await env.DB.prepare("SELECT me.* FROM media me WHERE me.id=? AND me.complete=1 AND me.expires_at>datetime('now') AND EXISTS(SELECT 1 FROM messages m JOIN chat_members cm ON cm.chat_id=m.chat_id WHERE m.media_id=me.id AND cm.user_id=?)").bind(mediaId,userId).first();if(!access)return new Response("Not found",{status:404});const parts=await env.DB.prepare("SELECT data FROM media_chunks WHERE media_id=? ORDER BY part").bind(mediaId).all();const total=parts.results.reduce((n,x)=>n+x.data.byteLength,0),out=new Uint8Array(total);let pos=0;for(const x of parts.results){const a=new Uint8Array(x.data);out.set(a,pos);pos+=a.length}return new Response(out,{headers:{"content-type":access.mime,"cache-control":"private,max-age=3600"}})}
 if(p==="/api/admin/password"&&method==="POST"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const b=await body(req);if(!b?.password||String(b.password).length<12)return json({error:"password_too_short"},400);const salt=crypto.getRandomValues(new Uint8Array(16));const hash=await hashPassword(String(b.password),salt);const enc=x=>btoa(String.fromCharCode(...x));await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,session_version=session_version+1 WHERE id=?").bind(enc(hash),enc(salt),userId).run();return json({ok:true})}
 if(p==="/api/admin/storage"&&method==="GET"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const meta=await env.DB.prepare("SELECT page_count,page_size FROM pragma_page_count(), pragma_page_size()").first().catch(()=>null);const media=await env.DB.prepare("SELECT COALESCE(SUM(size),0) bytes,COUNT(*) files FROM media WHERE complete=1").first();const messages=await env.DB.prepare("SELECT COUNT(*) count FROM messages").first();const dbBytes=Number(meta?.page_count||0)*Number(meta?.page_size||0);return json({db_bytes:dbBytes,media_bytes:Number(media?.bytes||0),files:Number(media?.files||0),messages:Number(messages?.count||0),limit_bytes:10*1024*1024*1024,exact:!!meta})}
 if(p==="/api/admin/users"&&method==="GET"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const r=await env.DB.prepare("SELECT id,username,role,subscription_expires_at,created_at FROM users ORDER BY id").all();return json(r.results)}
 if(p==="/api/admin/subscription"&&method==="POST"){if(!(await isAdmin(env,userId)))return json({error:"admin_required"},403);const b=await body(req),days=Number(b?.days);if(!b?.user_id||!Number.isInteger(days)||days<1||days>3650)return json({error:"invalid"},400);const r=await env.DB.prepare("UPDATE users SET subscription_expires_at=datetime('now','+' || ? || ' days') WHERE id=?").bind(days,b.user_id).run();if(!r.meta?.changes)return json({error:"user_not_found"},404);return json({ok:true})}
 return new Response("Not found",{status:404})
}
export default {async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname.startsWith("/api/")){try{return await route(req,env)}catch(e){return json({error:"server_error",message:String(e?.message||e)},500)}}return env.ASSETS.fetch(req)},async scheduled(controller,env,ctx){ctx.waitUntil((async()=>{await env.DB.prepare("DELETE FROM media_chunks WHERE media_id IN (SELECT id FROM media WHERE expires_at<=datetime('now') OR (complete=0 AND created_at<=datetime('now','-1 day')))").run();await env.DB.prepare("DELETE FROM media WHERE expires_at<=datetime('now') OR (complete=0 AND created_at<=datetime('now','-1 day'))").run()})())}}
